stackrox/contributions

util-scripts/policy-update/README.md
util-scripts/policy-update/policy-update.sh

This script is for managing stackrox policies in a gitops model. The idea is to save
policy definition files in VCS and run this script agains the policy definition files
when they are merged into master.

Reconcile StackRox policy with input file

---

ci/Tekton/Tasks/rox-deployment-check-task.yml
ci/Tekton/Tasks/rox-image-check-task.yml
ci/Tekton/Tasks/rox-image-scan-task.yml

Added a tag to image reference in Tekton Pipelines examples.
The tasks create pods that run the `roxctl` cli on `centos` images with the `latest` tag.
The pods fail to create when the `Latest tag` system policy is enforced on the `Deploy` lifecycle (The admission controller does not allow the creation of the task pods) in Stackrox.
Adding a tag to the `centos` image fixes the issue.

Added tag to centos images in Tekton pipelines tasks

---

ci/Tekton/Sample/rox-pipeline.yml
ci/Tekton/Tasks/rox-image-scan-task.yml

When executing this example the scan task reported that the --format option is no longer available. I updated it to --output which does not appear to take the "pretty" option, so I also changed it to output as json as part of the example.

update to work with latest roxctl

---

util-scripts/export-cves-to-csv/create-csv.sh

The original script uses violations of the policy "Fixable CVSS > 7", which has been disabled in ACS. This just changes the default policy name to the current "Fixable Severity at least Important"

changing policy name to examine to "fixable severity at least important"

---

api-examples/simple-alerts.md

Example of the various query types supported by API calls to /v1/alerts

adding a set of simple alert examples

---

backups/cron-backup.yaml
backups/readme.md
backups/retrieve-backups-pod.yaml

Developed for customer with limited cluster access and only access to storage via OCP PV/PVCs. Possibly of help to others. This was kept as simple as possible to a "new to K8s team".

cron based backups of ACS

---

util-scripts/export-cves-to-csv/create-csv.sh

The current script does not include the cluster name or ID and does not include the namespace name and ID. Many of my customers use this tool to export reports from ACS. They run multiple clusters with multiple tenants and would like to be able to easily distinguish which parts are coming from which.
I updated the script to retain the current output unless the user overrides this behavior with a VERSION flag. By defaulting to the original "v1", any tooling built on the output of this script will continue to work using the original format. Customers that want to use the second version can simply set VERSION="v2" when running the tool

Add support for multiple clusters and include namespace

---

util-scripts/roxctl-grace-period/README.md
util-scripts/roxctl-grace-period/grace.py

Example python script to parse the output of "roxctl image scan" to break down fixable images into two categories: those CVEs that were published less than X days ago ("in grace") and those published more than X days ago ("out of grace").
Intended as an example for build-time implementation of an automatic grace period for newly discovered CVEs.

roxctl-grace-period

---

util-scripts/listening-endpoints/listening-endpoints.sh

Adds the ability to filter out listening endpoints created by control plane components from the listening endpoints service. Also adds the ability to do the reverse and only show listening endpoints created by control plane components.

Jv filter control plane components in listening_endpoints

---

policies/CVE-2021-4034-build-deploy.json
policies/polkit-execution.json
policies/polkit-in-image.json

Adds policies that can be used to mitigate a PolKit local privilege escalation vulnerability:
* Scan images and detect `polkit` and `policykit-1` packages vulnerable to CVE-2021-4034
* Identify `polkit` or `policykit-1` packages present in container images
* Detect `pkexec` usage at runtime. 
These policies can be validated by inspecting the `quay.io/the-worst-containers/pwnkit:v0.2` image:
```
roxctl -e "stackrox" --insecure-skip-tls-verify image check --image  quay.io/the-worst-containers/pwnkit:v0.2
Policy check results for image: quay.io/the-worst-containers/pwnkit:v0.2
(TOTAL: 5, LOW: 3, MEDIUM: 0, HIGH: 1, CRITICAL: 1)
+--------------------------------+----------+--------------+--------------------------------+--------------------------------+--------------------------------+
| …
```

Add PolKit local privilege escalation policies

---

util-scripts/listening-endpoints/listening-endpoints.sh

Process name is more accurate and more consistent with other APIs and the UI.

Jv change column name to process name

---

util-scripts/listening-endpoints/listening-endpoints.sh

Changed the "Process name" column to "Exec file path" in the listening endpoints script.
Example
```
Exec file path                           PID       Port    Proto   Namespace       clusterId                                podId                                                   containerName       
/usr/pgsql-13/bin/postgres               17723     5432    tcp     stackrox        71b39c1a-72e8-4b72-8a0c-da2df32bfa77     central-db-784dbb68dc-nf2g2                             central-db          
/scanner                                 17322     8080    tcp     stackrox        71b39c1a-72e8-4b72-8a0c-da2df32bfa77     scanner-57d99448cd-p8xwg                                scanner             
/scanner                                 14661     9090    tcp     stackrox …
```

Jv change process name to exec file path

---

util-scripts/violations-to-csv/violations-to-csv.sh

Script currently pulls cluster and namespace from `deployment` object which is deprecated - it should use `commonEntityInfo`. Furthermore for non-deployment alerts (such as when you create an audit log based policy), deployment name doesn't make sense.
This change adds a "Resource Type" column as well to make it clear which resource the alert is for.

Update violations-to-csv to account for non-deployment based alerts

---

util-scripts/export-all-policies/README.md
util-scripts/export-all-policies/export-all-policies.sh

Keeping it pretty simple. Future optimization could include supporting limiting which policies get exported (by id, name, category or query)

Add simple script to export all policies as CSV

---

compliance/scan-compliance.sh

This script will scan compliance cluster by cluster, which is helpful if the Scan Now button the UI is causing OOMs (which scans clusters and standards in parallel)

Add script to scan compliance cluster by cluster to reduce memory

---

policies/leaky-vessels.json

A policy for CVE-2024-21626, described here: https://access.redhat.com/security/cve/cve-2024-21626
You can test this image with a simple Containerfile:
```
FROM registry.access.redhat.com/ubi9/ubi
WORKDIR /proc/self/fd/7
```
A `roxctl image check` will then show that the image is vulnerable:
```
+--------------------------------+----------+--------------+--------------------------------+--------------------------------------+--------------------------------+
| Leaky Vessels: runc container  |   HIGH   |      -       |      CVE-2024-21626 is a       |      - Dockerfile line 'WORKDIR      |      Remove Containerfile      |
|            breakout            |          |              |   vulnerability in the runc    |        /proc/self/fd/7' found        |   lines resembling 'WORKDIR    |
| …
```

Add leaky vessels policy

---

util-scripts/listening-endpoints/listening-endpoints.sh

Currently turning the json with deployments to a list of deployments is slow, since the script loops through the deployments in the json one by one. Now all of the deployments are gotten in one step. The script is still slow in other places.

Jv get deployments faster

---

util-scripts/vuln-violation-details/vulnvdetails.sh

spurred by a Slack request for retrieving the full details of vulnerability policy violations.
The data returned by the alert api endpoint is a "slim" list of violations. details of each violation must be retrieved individually. This script uses the list of IDs from /v1/alerts in order to loop through each violation.
Easily modified to support other policy search filters.

example script for getting violation details for a policy

---

vulnerability-management/export-workloads/README.md
vulnerability-management/export-workloads/export-workloads.py
vulnerability-management/export-workloads/export-workloads.sh

Add explicit example scripts for the `/v1/export/vuln-mgmt/workloads` API.
I added one shell script and one python example. Both examples make use of the streaming nature of the API.

ROX-24175: vuln-mgmt export API examples

---

util-scripts/generate_violations_csv/README.md
util-scripts/generate_violations_csv/generate_violations_csv.py
util-scripts/generate_violations_csv/requirements.txt

This PR generate csv report that contains enabled violations in ACS 
* Gets ACS API key and API Central URL as environment variables
* Mandatory `--query_scope` will limit the query for specific cluster, specific cluster and namespace or all violations
* Pulls all violations based on the query provided, loop through every violation (aka `alert_id`) and pull the image(s) violating the policy 
* Saves an csv files under generated `reports` folder

generate_violations_csv script 

---

policies/oc-debug-runtime.json

Adds a new policy to detect attempts to access pods using `oc debug`. 
Note that `oc debug` doesn't invoke `kubectl exec` or similar commands to access the pod, instead creating a new `debug` pod configured the same as the original pod. For this reason we need to look at process activity inside pods (that look like `/bin/sh` or `/bin/bash`), and account for the ability of users to customise the shell via `oc debug --shell`.
Ideally we would distinguish this activity based on pod name or pod annotations like `debug.openshift.io/source-container`, but this is not currently possible for runtime policies. Instead we label this as "Possible oc debug activity", and guide users towards the OpenShift audit logs for validation.

Create a policy to detect 'oc debug'

---

Readme.md
guides/cloud-provider-integrations/azure-service-principal-m2m-auth.md

This PR is adding a guide on how to setup Azure Entra ID service principals and ACS machine-to-machine authentication to use short-lived tokens with `roxctl`.
P.S. This is a 1-to-1 copy of docs linked in [ROX-24421](https://issues.redhat.com/browse/ROX-24421) with one to two tweaks.

Add Azure m2m auth with ACS
